skeletons.json
Added a skeleton for Vue projects.
=> Added Vue skeleten

skeletons.json
Weekend Brunch is a Brunch Skeleton powered by Electron, Brunch and Sass and Babel
=> Added Weekend Brunch to skeletons.json

skeletons.json
it would come in handy to initialize the skeleton for electron project : )
=> includes alias for electron skeleton

skeletons.json
ES6 starter project for Ghost theme development with Casper included as reference.
=> Added Ghost theme with brunch

skeletons.json
Some simple site generator for ones who love Jade and Stylus.
There is README with short explanation of structure inside.
If it is worth, add it :)
=> Add lazy-static-site-gen

skeletons.json
I wanted to add my package for starting a webgl project with Three.js
Thx !
=> New package to Three.js and es2015

skeletons.json
* Add `brunch-with-cocktails` to registry
* Move a few `brunch/` repos back to the top of the list.
=> Brunch with cocktails

skeletons.json
Adaptation of brunch-with-elm for using electron
=> Add brunch-with-elm-and-electron setup

skeletons.json
Adding repo with testing support with jest to the list of skeletons
=> Ritabrata - Adding React-Jest to skeletons

skeletons.json
=> added inferno skeleton

skeletons.json
Infernojs created an official brunch-with-inferno repository.
Updated *url* of the skeleton to the official brunch-with-inferno repository.
=> updated brunch-with-inferno url

skeletons.json
Added "Brunch with Vuety" skeleton to the current list of skeletons
=> Added "Brunch with Vuety"

skeletons.json
Hi there,
I just made a little skeleton for those who want to build a web app backed with ASP.NET and having Knockout & jQuery for the frontend.
Kind regards
Achim
=> Added aspnet-knockout

.travis.yml, package.json
It's required to switch on travis to make it works.
Here's test example
https://github.com/denar90/skeletons/pull/2
https://travis-ci.org/denar90/skeletons/builds/218604710
=> Add travis, validate skeletons syntax

skeletons.json
My brunch skeleton, with:
- Babel/ES6,
- React/Redux
- Bootstrap
- jQuery
- Sass
- AirBnB ESLint
https://github.com/m4ttsch/brunch-with-sangria
=> Brunch with sangria.

skeletons.json
Based on the official React skeleton.
=> Added Preact skeleton

skeletons.json
=> add skunch

skeletons.json
New skeleton:
https://github.com/buckle2000/static-so-elegant
=> Add so-elegant

skeletons.json
=> Add vue-mdc alias

skeletons.json
=> Fix some linkrot
